# Generated by Django 3.2 on 2023-08-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_desctiption_actor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value']},
        ),
    ]
