# Generated by Django 3.2 on 2023-08-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_ratingstar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
